graph LR
    %% MermaidJS workflow graph for Bike or E-bike TSP
    %% Use https://mermaid-js.github.io/mermaid-live-editor/ to edit
    Options[Booking options] -.->|Reserving a bike | Reserved
    Reserved -->|Unlocking| Activated2[Activated]
    Reserved -.->|Subject to a fee| Cancelled
    Reserved -.->|Denied by TSP| Rejected
    Reserved2[Reserved] -->|Unlocking| Activated
    Activated -->|Ride finished| Expired
    Activated -->|Lock and keep reserved| On_hold
    Expired -->|Final price received| Finished
    On_hold -->|Unlock| Activated
    Activated -.->|Denied by TSP| Rejected2[Rejected]
    On_hold -.->|Denied by TSP| Rejected2[Rejected]
    style Cancelled color:red,stroke-dasharray: 5, 5
    style Rejected color:red,stroke-dasharray: 5, 5
    style Rejected2 color:red,stroke-dasharray: 5, 5
