graph TD
  label1(Shared car state flow)
  %% MermaidJS workflow graph for Taxi TSP
  %% Use https://mermaid-js.github.io/mermaid-live-editor/ to edit
  KYC[KYC] -.->|Check driver license| Reserved
  Options[Booking options] -.->|Create the booking| Reserved
  Reserved -->|Unlock| Activated
  Reserved -.->|Subject to a fee| Cancelled
  Reserved -->|Timed-out| Expired2[Expired]
  Activated2[Activated] -->|Ride finished| Expired
  Activated2[Activated] -->|Park| On_hold[On hold]
  Expired -->|Final price received| Finished
  On_hold[On hold] -->|Ride finished| Expired
  On_hold[On hold] -->|Unpark| Activated2
  style Cancelled color:red,stroke-dasharray: 5, 5
  style Expired2 color:red,stroke-dasharray: 5, 5
  style label1 stroke-width:2px,color:black,stroke:black,fill:white
  style KYC stroke-dasharray:5,5
