sequenceDiagram
  %% MermaidJS sequence on how returning a bike to dock station works
  %% when you need to enter PIN to put the bike in the dock
  participant User as 👤 UI
  participant App as ⚙️ Backend
  participant TSP as 🚲 TSP API
  participant Dock as 🚪 Dock
  Note over User,TSP: Returning a bike to dock
  User->>App: Return bike
  TSP->>User: Docking stations?
  User->>TSP: Update state "ON_HOLD" with a dock ID
  TSP->>User: Return booking with dock PIN code
  User->>Dock: Enter docking code on station
  TSP->>App: Receive state "EXPIRED"
