graph TD
  label1(Docked bike state flow)
  %% MermaidJS workflow graph for docker Bike or E-bike TSP
  %% Use https://mermaid-js.github.io/mermaid-live-editor/ to edit
  Options[Booking options] -.->|Reserving a bike | Reserved
  Reserved -->|Unlocking| Activated2[Activated]
  Reserved -.->|Subject to a fee| Cancelled
  Reserved -.->|Denied by TSP| Rejected
  Reserved -->|Reservation timed-out| Expired2[Expired]
  Activated -->|Reserve a return dock| On_hold
  On_hold[On hold] -->|Cancel return| Activated
  On_hold[On hold] -->|New attempt to return| On_hold[On hold]
  Activated -.->|Denied by TSP| Rejected2[Rejected]
  On_hold[On hold] -->|Ride finished| Expired
  Expired -->|Final price received| Finished
  style Cancelled color:red,stroke-dasharray: 5, 5
  style Rejected color:red,stroke-dasharray: 5, 5
  style Rejected2 color:red,stroke-dasharray: 5, 5
  style Expired2 color:red,stroke-dasharray: 5, 5
  style label1 stroke-width:2px,color:black,stroke:black,fill:white
