sequenceDiagram
  %% MermaidJS sequences for docked bike interaction
  %% Use https://mermaid-js.github.io/mermaid-live-editor/ to edit
  %% For docking and undocking a bike you need to provide a PIN code 
  participant User as 👤 User
  participant App as 📱 App
  participant TSP as 🚲 API
  participant Dock as 🚪 Dock
  participant Finance as 👩‍💼 Finance
  Note over User,TSP: Dock based bike sharing
  User->>App: Options
  App->>TSP: Options
  TSP->>User: Show docks, bikes and prices
  User-->>App: Initial payment
  User->>TSP: Create booking
  User->>Dock: Undocking code
  TSP->>User: Receive state "ACTIVATED"
  Note over User,TSP: Bike ride started
  User->>App: Return bike
  TSP->>User: Docking stations
  User->>TSP: Ask PIN code for docking station
  User->>Dock: Enter docking code on station
  TSP->>User: Receive state "EXPIRED"
  TSP->>App: Receive state "FINISHED"
  Note over App,TSP: Final price
  User-->>App: (Off-session) payment
  loop Monthly
    Note over TSP,Finance: Payment according to invoice
    TSP->>Finance: Invoice 
  end
