%% MermaidJS workflow graph for Taxi TSP
%% Use https://mermaid-js.github.io/mermaid-live-editor/ to edit
graph LR
    Options[Booking options] -.->|Creating the booking| Reserved
    Confirmed -.->|Subject to a fee| Cancelled
    Confirmed -.->|Driver rejected| Rejected
    Reserved -.->|No driver| Rejected
    Reserved -->|Driver found| Confirmed
    Reserved -.->|Subject to a fee| Cancelled2["Cancelled"]
    Confirmed2[Confirmed] -->|Waiting for pickup| Arrived
    Arrived -->|Ride started| Activated
    Activated -->|Ride finished| Expired
    Expired -->|Final price received| Finished
    style Cancelled color:red,stroke-dasharray: 5, 5
    style Cancelled2 color:red,stroke-dasharray: 5, 5
    style Rejected color:red,stroke-dasharray: 5, 5
